import "./indicators/bollinger_e";
import "./indicators/bollinger-percent-b_e";
import "./indicators/bollinger-bandwidth_e";
import "./indicators/ema_e";
import "./indicators/zigzag_pp";
import "./indicators/atr";
import "./indicators/rs";
import "./indicators/gaps_pp";
import "./indicators/highest_range";